name: Advanced Usage

on:
  push:
    paths:
      - 'Przedmiot/**.md'
    branches:
      - master
    # tags:
    #   - '*'

jobs:
  prepare_output:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: prepare_output
        run: |
          mkdir -p output

  get_files:
    runs-on: ubuntu-latest
    needs: prepare_output
    outputs:
      files: ${{ steps.files_list.outputs.files }}
    steps:
      - name: get file list
        id: files_list
        run: echo "::set-output name=matrix::$(ls Przedmiot/*.md | jq -R -s -c 'split("\n")[:-1]')"

# -----------------------------------------------------------------------------

  list_files:
    needs: get_files
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file: ${{ fromJson(needs.get_files.outputs.files) }}
    steps:
      - name: list files
        run: |
          echo "${{ file }}"

  # convert_via_pandoc:
  #   needs: get_files
  #   runs-on: ubuntu-latest
  #   strategy:
  #       matrix:
  #           file: ${{ fromJson(needs.get_files.outputs.files) }}
  #   steps:
  #     - uses: docker://pandoc/latex:2.9
  #       with:
  #         args: >-
  #           --output=output/result.pdf ${{ matrix.file }}
  #           Przedmiot/Fizyka.md -o fizyka.pdf --from=markdown --to=pdf

  # pack:
  #   needs: convert_via_pandoc
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/upload-artifact@v3
  #       with:
  #         name: output
  #         path: output
