name: Pack it all

on:
  push:
    paths:
      - 'Przedmiot/**.md'
    branches:
      - master
    # tags:
    #   - '*'

jobs:
  prepare_output:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: prepare_output
        run: |
          mkdir -p output

  get_files:
    runs-on: ubuntu-latest
    needs: prepare_output
    outputs:
      files: ${{ steps.files_list.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - name: get file list
        id: files_list
        run: echo "matrix=$(ls Przedmiot/*.md | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT

  list_files:
    needs: get_files
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file: ${{ fromJson(needs.get_files.outputs.files) }}
    steps:
      - uses: mad9000/actions-find-and-replace-string@3
        id: without_path
        with:
          source: ${{ matrix.file }}
          find: 'Przedmiot/'
          replace: ''
      - uses: mad9000/actions-find-and-replace-string@3
        id: without_extension
        with:
          source: ${{ steps.without_path.outputs.result }}
          find: '.md'
          replace: ''
      - name: list files
        run: |
          echo "${{ steps.without_path.outputs.result }}.pdf"

# -----------------------------------------------------------------------------

  # convert_via_pandoc:
  #   needs: get_files
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       file: ${{ fromJson(needs.get_files.outputs.files) }}
  #   env:
  #     path: ${{ matrix.file }}
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: docker://pandoc/latex:latest
  #       with:
  #         args: >-
  #           --output=output/${env.file}.pdf
  #           --from=markdown
  #           --to=pdf
  #           ${env.path}/${env.file}

  # pack:
  #   needs: convert_via_pandoc
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/upload-artifact@v3
  #       with:
  #         name: output
  #         path: output
