name: Advanced Usage

on:
  push:
    paths:
      - 'Przedmiot/**.md'
    branches:
      - master
    # tags:
    #   - '*'

jobs:
  get_files:
    runs-on: ubuntu-latest
    outputs:
      files: ${{ steps.files_list.outputs.files }}
    steps:
      - uses: actions/checkout@v3

      - name: get file list
        id: files_list
        run: |
          echo "files=$(printf '"%s" ' ./Przedmiot/*.md)" > $GITHUB_OUTPUT

  list_files:
    needs: get_files
    runs-on: ubuntu-latest
    steps:
      - name: list files
        run: |
          echo "${{ steps.files_list.outputs.files }}"

  # convert_via_pandoc:
  #   needs: get_files
  #   runs-on: ubuntu-latest
  #   strategy:
  #       matrix:
  #           manifest: ${{ fromJson(needs.get_files.outputs.matrix) }}
  #   steps:
  #     - uses: docker://pandoc/latex:2.9
  #       with:
  #         args: >-
  #           --output=output/result.pdf ${{ steps.files_list.outputs.files }}
  #           Przedmiot/Fizyka.md -o fizyka.pdf --from=markdown --to=pdf

  # pack:
  #   needs: convert_via_pandoc
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/upload-artifact@v3
  #       with:
  #         name: output
  #         path: output
